name: ST-SkinBook
main: net.starly.skinbook.SkinBookMain
author: Starly Team
website: http://starly.kr/discord

description: SkinBook Plugin.

version: 1.0
api-version: 1.14

commands:
  skinbook:
    description: 스킨북 명령어.
    aliases: [ 스킨북, sb, skb ]