name: ST-SkinBook
main: net.starly.skinbook.SkinBookMain
author: Starly Team
website: http://starly.kr/

description: SkinBook Plugin.

softdepend:
  - ST-Core

version: 1.0.5
api-version: 1.14

commands:
  skin-book:
    description: 스킨북 명령어.
    aliases: [ 스킨북, sb ]